FROM node:16 as build
WORKDIR /usr/app/
COPY ./ ./
RUN npm ci && npm run build

FROM nginxinc/nginx-unprivileged:alpine as RUNTIME
COPY ./.nginx/nginx.conf /etc/nginx/nginx.conf
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /usr/app/dist /usr/share/nginx/html

USER 1000

EXPOSE 8080
ENTRYPOINT ["nginx", "-g", "daemon off;"]